### ISSUE TITLE
Capacitor 3 support

### ISSUE THREAD

**Issue by gillarf** [WuglyakBolgoink/cordova-plugin-iroot#55]
Hi there - I can't get this to work in Capacitor 3. I saw elsewhere it can be added as a plugin in Capacitor 2, but I tried this and it broke the app.

i.e.

import { Plugins } from '@capacitor/core';
const { IRoot } = Plugins;

ngOnInit() {
    IRoot.isRooted(()=>{
      //do whatever
   });
}
....
Doesn't work for me, and in case is deprecated.

Any help much appreciated.

**Comment by WuglyakBolgoink** [comment]
Hallo @gillarf 

are you sure, that capacitor added my plugin to own `Plugins`?

I think, you must add this plugin directly without '@capacitor/core'....

**Comment by WuglyakBolgoink** [comment]
@gillarf tested with emulator


1. install plugin `npm i cordova-plugin-iroot -E`
2. Sync new changes `npx cap sync`
3. in `tsconfig.app.json` add
```ts
{
...
"compilerOptions": {
    ...
    "typeRoots": [
      "node_modules/cordova-plugin-iroot/types"
    ]
  },
},
...
```
4. in controller declare global `IRoot` variable
example:
```ts
import { Component, OnInit, Input } from '@angular/core';

declare var IRoot: IRootPlugin;

@Component()
export class ExploreContainerComponent implements OnInit {

  constructor() {}

  ngOnInit() {
    try {
      IRoot.isRooted((result) => {
        alert('ok');
        console.log('[ExploreContainerComponent.] IRoot.isRooted result', result);
      }, (error) => {
        alert('not ok');
        console.error('[ExploreContainerComponent.] IRoot.isRooted error', error);
      });
    } catch (error) {
      console.error('[ExploreContainerComponent.ngOnInit] error', error);
    }
  }
}
```
5.  run the app 
`ionic capacitor sync && ionic capacitor run android`



Currently I'm not supported capacitor framework, and maybe do another plugin for this if anyone else need this

**Comment by gillarf** [comment]
Thanks for such a details reply @WuglyakBolgoink - much appreciated

**Comment by BenOtsoa** [comment]
Hi @WuglyakBolgoink ,
Thanks a lot for your contribution. 
Just for you to know, I tried to use your plugin via macOS 11.2.3 combined with Android Studio and also XCode.
Every method of the plugin return 'false' except 'togetDeviceInfo()' that returns the proper datas.
I figured out that with the exact same project and piece of your code, it runs well on windows.
Don't know if could be due to my apple configuration or else.. 
What is also weird is that the official capacitor Plugin (Device one) succeeded in finding that I was running my app on a virtual machine on mac/android studio or xcode while your plugin 'isRunningOnEmulator' one can't. 

Don't know if other apple developers faced the same behavior. 

Whatever, it was just fort the report. Thanks again, I take your's because of the root detection that is not available on other plugins. Many many thanks

Benjamin

**Comment by WuglyakBolgoink** [comment]
Hallo @BenOtsoa !

1) the iOS and Android implementation a little bit different and contain different checks, which not the same across the plattforms.

2) What you mean exactly

>  it runs well on windows.

I just started with learning `capacitor`. I will check later how the `capacitor` device plugin work exactly...

**Comment by BenOtsoa** [comment]
> What you mean exactly
>>it runs well on windows.
Hey, I meant that I tested on windows and apple systems. No problem on windows, it worked fine. :)

**Comment by fathanyr** [comment]
Hi, thanks for your contribution, i'll be happy if u made this compatible for Capacitor v3, thank you!

**Comment by WuglyakBolgoink** [comment]
@fathanyr this is in my todo for coming release

**Comment by gillarf** [comment]
Hi @WuglyakBolgoink - just a quick question about testing in the emulator - are emulators naturally rooted, or do you need to do something to make them behave so? Our emulator seems to think it is not rooted.

Thanks in advance.
